
backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pagina"
    label: "Página de inicio"
    files:
      - file: "index.html"
        label: "Inicio"
        name: "inicio"
        fields:
          - { label: "Contenido", name: "body", widget: "markdown" }
